version: "3.9"
services:
  python:
    volumes: 
      - .:/code 
    build: .
    #stdin_open: true 
    #tty: true        
    ports:
      - 8888:8888
    command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.password=''